# Arrays using NumPy  

**Author:** Praveen Kumar G (22MID0300)  
**Date:** September 14, 2025  

---

## Purpose  
To demonstrate the fundamental concepts of NumPy arrays in Python.  

---

## Topics Covered  
- **Array Creation** → From lists, zeros, ones, ranges, and linspace.  
- **Array Attributes** → Shape, size, dimensions, and data types.  
- **Indexing & Slicing** → Accessing elements, rows, columns, and sub-arrays.  
- **Array Operations** → Arithmetic, broadcasting, universal functions, and comparisons.  
- **Reshaping & Flattening** → Modifying array shapes, flattening arrays using ravel and flatten.  
- **Statistical Functions** → Mean, median, std, variance, min, max, and sum (with axis operations).  
- **Random Module** → Generating random numbers, integers, and reproducible results using seeds.  
- **Practical Example** → Student marks analysis showing NumPy’s real-world applications.  


#  Arrays with NumPy

##  1. Getting Started with NumPy
`NumPy` stands for **Numerical Python** and is a fundamental package for scientific computing in Python.

---

###  Key Features
- **ndarray (N-Dimensional Array):**
  - Similar to Python lists but faster and more memory-efficient.
- **Vectorized Operations:**
  - Perform arithmetic on arrays without writing loops.
- **Math Utilities:**
  - Linear algebra, statistics, random number generation, etc.

---

###  Why prefer NumPy arrays over Python lists?
1. **Speed:**  
   NumPy arrays are stored in **contiguous memory blocks**, enabling faster processing.
2. **Convenience:**  
   You can apply operations directly on the entire array.
3. **Efficiency:**  
   Less memory usage compared to Python lists.

print("NumPy Array:", np_array + 10)


In [3]:
# Importing NumPy
import numpy as np

# Comparing Python list vs NumPy array
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python List:", python_list)
print("NumPy Array:", numpy_array)

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]


## 2. Creating NumPy Arrays

There are multiple ways to create arrays in NumPy:

1. **From a Python list or tuple** using `np.array()`.
2. **Arrays filled with zeros or ones** using `np.zeros()` and `np.ones()`.
3. **Range of numbers** using `np.arange(start, stop, step)`.
4. **Evenly spaced numbers** using `np.linspace(start, stop, num_points)`.

These methods are essential for scientific computing and simulations.


In [5]:
# 1. Creating array from list
arr1 = np.array([10, 20, 30, 40, 50])

# 2. Array of zeros
arr2 = np.zeros((3, 4))  # 3 rows, 4 columns

# 3. Array of ones
arr3 = np.ones((2, 5))  # 2 rows, 5 columns

# 4. Range of numbers
arr4 = np.arange(0, 20, 2)  # Numbers from 0 to 18 with step size 2

# 5. Evenly spaced numbers
arr5 = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1

print("Array from List:", arr1)
print("Zeros Array:\n", arr2)
print("Ones Array:\n", arr3)
print("Range Array:", arr4)
print("Linspace Array:", arr5)

Array from List: [10 20 30 40 50]
Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Range Array: [ 0  2  4  6  8 10 12 14 16 18]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


## 3. Array Attributes

Each NumPy array has important attributes that describe its structure:

- **`ndim`** → Number of dimensions (axes).  
- **`shape`** → Tuple representing size along each dimension.  
- **`size`** → Total number of elements in the array.  
- **`dtype`** → Data type of array elements.  

These attributes are useful to quickly understand the structure of the data.


In [7]:
# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Checking array attributes
print("Array:\n", arr)
print("Number of Dimensions (ndim):", arr.ndim)
print("Shape (rows, cols):", arr.shape)
print("Total Elements (size):", arr.size)
print("Data Type (dtype):", arr.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
Number of Dimensions (ndim): 2
Shape (rows, cols): (2, 3)
Total Elements (size): 6
Data Type (dtype): int32


## 4. Array Indexing and Slicing

Just like Python lists, we can access individual elements and slices of arrays:

- **1D Arrays:** Use `[index]` and `[start:end:step]`.  
- **2D Arrays:** Use `[row, col]` for single elements.  
- Slicing allows extracting sub-arrays, rows, or columns.


In [9]:
# 1D Array
arr1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1d)
print("Element at index 2:", arr1d[2])     # third element
print("Slice [1:4]:", arr1d[1:4])          # elements from index 1 to 3

# 2D Array
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\n2D Array:\n", arr2d)

# Accessing single element
print("Element at row 1, col 2:", arr2d[1, 2])

# Extracting a row
print("Second row:", arr2d[1, :])

# Extracting a column
print("First column:", arr2d[:, 0])

# Sub-matrix
print("Sub-matrix (first 2 rows, first 2 cols):\n", arr2d[0:2, 0:2])

1D Array: [10 20 30 40 50]
Element at index 2: 30
Slice [1:4]: [20 30 40]

2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
Second row: [40 50 60]
First column: [10 40 70]
Sub-matrix (first 2 rows, first 2 cols):
 [[10 20]
 [40 50]]


## 5. Array Operations

NumPy arrays support a wide variety of operations:

1. **Elementwise Arithmetic**
   - Addition, subtraction, multiplication, division.
   - Operations are applied to each element.

2. **Broadcasting**
   - NumPy allows operations between arrays of different shapes if they are compatible.
   - Example: Adding a scalar to an array automatically applies the operation to all elements.

3. **Universal Functions (ufuncs)**
   - Optimized functions that work elementwise on arrays.
   - Examples: `np.sqrt`, `np.exp`, `np.log`, `np.sin`, `np.cos`.

4. **Comparison Operators**
   - Returns boolean arrays (`True`/`False`) for conditions.
   - Useful for **boolean indexing** and filtering.


In [11]:
# Creating two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# 1. Elementwise arithmetic
print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)

# 2. Broadcasting (adding scalar)
print("\nBroadcasting (add 5):", a + 5)

# 3. Universal functions
print("\nSquare Root:", np.sqrt(a))
print("Exponential:", np.exp(a))
print("Sine Values:", np.sin(a))

# 4. Comparison operators
print("\nComparison (a > 2):", a > 2)
print("Comparison (b == 20):", b == 20)

# Boolean indexing
print("Elements of a greater than 2:", a[a > 2])

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]

Broadcasting (add 5): [ 6  7  8  9 10]

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine Values: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Comparison (a > 2): [False False  True  True  True]
Comparison (b == 20): [False  True False False False]
Elements of a greater than 2: [3 4 5]


## 6. Reshaping and Flattening

NumPy allows changing the shape of arrays without altering their data.

1. **Reshaping**
   - Use `.reshape(rows, cols)` to change the structure.
   - The number of elements must remain the same.

2. **Flattening**
   - Convert multi-dimensional arrays into 1D.
   - Methods:
     - `.ravel()` → Returns a **view** (changes reflect in original array).
     - `.flatten()` → Returns a **copy** (changes do not affect original).


In [13]:
# Creating a sequential array
arr = np.arange(1, 13)  # numbers from 1 to 12
print("Original Array:", arr)

# 1. Reshape into 3x4 matrix
reshaped = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped)

# 2. Flattening using ravel
ravelled = reshaped.ravel()
print("\nFlattened using ravel:", ravelled)

# 3. Flattening using flatten
flattened = reshaped.flatten()
print("Flattened using flatten:", flattened)

# Modifying ravel result affects original
ravelled[0] = 99
print("\nAfter modifying ravelled array:")
print("Ravelled:", ravelled)
print("Original reshaped array:\n", reshaped)

# Modifying flatten result does NOT affect original
flattened[1] = 88
print("\nAfter modifying flattened array:")
print("Flattened:", flattened)
print("Original reshaped array remains unchanged:\n", reshaped)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened using ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Flattened using flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravelled array:
Ravelled: [99  2  3  4  5  6  7  8  9 10 11 12]
Original reshaped array:
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

After modifying flattened array:
Flattened: [ 1 88  3  4  5  6  7  8  9 10 11 12]
Original reshaped array remains unchanged:
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 7. Statistical and Mathematical Functions

NumPy provides many built-in functions to perform **statistics and mathematics** efficiently:

### Common Statistical Functions
- **`np.mean()`** → Average value.  
- **`np.median()`** → Middle value.  
- **`np.std()`** → Standard deviation (spread of data).  
- **`np.var()`** → Variance.  
- **`np.sum()`** → Sum of all elements.  
- **`np.min()` / `np.max()`** → Minimum and maximum values.  

### Axis Parameter
- **`axis=0`** → Apply function column-wise (down each column).  
- **`axis=1`** → Apply function row-wise (across each row).  


In [15]:
# Creating a 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Array:\n", arr)

# 1. Basic statistics
print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Sum:", np.sum(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# 2. Using axis
print("\nColumn-wise Mean (axis=0):", np.mean(arr, axis=0))
print("Row-wise Sum (axis=1):", np.sum(arr, axis=1))

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Mean: 50.0
Median: 50.0
Standard Deviation: 25.81988897471611
Variance: 666.6666666666666
Sum: 450
Minimum: 10
Maximum: 90

Column-wise Mean (axis=0): [40. 50. 60.]
Row-wise Sum (axis=1): [ 60 150 240]


## 8. Random Module in NumPy

NumPy has a powerful random module (`np.random`) to generate random numbers for simulations, testing, and machine learning.

### Common Functions:
1. **`np.random.rand(d0, d1, ...)`**
   - Generates random numbers in the range `[0, 1)`.
   - Uniform distribution.

2. **`np.random.randn(d0, d1, ...)`**
   - Generates numbers from the **standard normal distribution** (mean = 0, std = 1).

3. **`np.random.randint(low, high, size)`**
   - Generates random integers between `low` and `high`.

4. **`np.random.seed(value)`**
   - Fixes the randomness → useful for reproducibility.
   - Same seed produces the same random numbers.


In [17]:
# 1. Random numbers between 0 and 1
rand_array = np.random.rand(3, 3)
print("Random array (0 to 1):\n", rand_array)

# 2. Random numbers from normal distribution
randn_array = np.random.randn(2, 4)
print("\nRandom array (normal distribution):\n", randn_array)

# 3. Random integers
randint_array = np.random.randint(1, 100, size=(5,))
print("\nRandom integers between 1 and 100:", randint_array)

# 4. Using seed for reproducibility
np.random.seed(42)
print("\nWith Seed 42, random numbers:", np.random.rand(3))
np.random.seed(42)
print("With Seed 42 again, same numbers:", np.random.rand(3))


Random array (0 to 1):
 [[0.54582314 0.4914407  0.17057003]
 [0.74129279 0.14872085 0.88574225]
 [0.69909592 0.09237698 0.27014825]]

Random array (normal distribution):
 [[ 0.20716287  0.71348343 -0.90546288  0.49912528]
 [-0.01233233 -1.64124073  1.58908623  2.50185626]]

Random integers between 1 and 100: [40 49  4 87 14]

With Seed 42, random numbers: [0.37454012 0.95071431 0.73199394]
With Seed 42 again, same numbers: [0.37454012 0.95071431 0.73199394]


## 9. Practical Example – Student Marks Analysis

Let’s combine multiple NumPy concepts in a small project.  
We will:

1. **Generate random student marks** for 5 subjects and 10 students.
2. **Analyze the marks** using statistical functions.
3. **Reshape and slice** data for specific insights.
4. **Apply boolean indexing** to find top-performing students.

This demonstrates how NumPy is useful in real-world data analysis.

In [19]:
# Step 1: Generate random marks (10 students, 5 subjects)
np.random.seed(101)  # reproducibility
marks = np.random.randint(40, 100, size=(10, 5))  # marks between 40 and 100

print("Marks of 10 students (rows) across 5 subjects (cols):\n", marks)

# Step 2: Analyze data
print("\nOverall Average Marks:", np.mean(marks))
print("Average Marks per Subject:", np.mean(marks, axis=0))
print("Average Marks per Student:", np.mean(marks, axis=1))

# Step 3: Find highest and lowest scoring student
total_marks = np.sum(marks, axis=1)
highest_student = np.argmax(total_marks)  # index of top student
lowest_student = np.argmin(total_marks)   # index of bottom student

print("\nTotal Marks of Each Student:", total_marks)
print("Top Student Index:", highest_student, "with Total Marks:", total_marks[highest_student])
print("Lowest Student Index:", lowest_student, "with Total Marks:", total_marks[lowest_student])

# Step 4: Boolean indexing - Students with average > 70
avg_per_student = np.mean(marks, axis=1)
print("\nStudents with Avg > 70:", np.where(avg_per_student > 70)[0])

Marks of 10 students (rows) across 5 subjects (cols):
 [[71 51 57 46 63]
 [51 87 49 53 80]
 [44 80 93 68 40]
 [86 45 52 69 80]
 [89 59 87 98 48]
 [91 69 91 99 74]
 [84 48 97 59 50]
 [52 71 83 63 40]
 [81 95 49 87 48]
 [76 59 75 68 47]]

Overall Average Marks: 68.04
Average Marks per Subject: [72.5 66.4 73.3 71.  57. ]
Average Marks per Student: [57.6 64.  65.  66.4 76.2 84.8 67.6 61.8 72.  65. ]

Total Marks of Each Student: [288 320 325 332 381 424 338 309 360 325]
Top Student Index: 5 with Total Marks: 424
Lowest Student Index: 0 with Total Marks: 288

Students with Avg > 70: [4 5 8]


## 10. Conclusion

In this notebook, we explored the basics of **NumPy for Arrays**:

- **Array Creation** → From lists, zeros, ones, ranges, and linspace.  
- **Array Attributes** → Shape, size, dimensions, and data types.  
- **Indexing & Slicing** → Accessing elements, rows, columns, and sub-matrices.  
- **Array Operations** → Arithmetic, broadcasting, universal functions, and comparisons.  
- **Reshaping & Flattening** → Changing shapes, flattening arrays using `ravel` and `flatten`.  
- **Statistical Functions** → Mean, median, std, variance, min, max, and sum (with axis operations).  
- **Random Module** → Generating random numbers, integers, and reproducible results using seeds.  
- **Practical Example** → Student marks analysis demonstrated how NumPy is applied in real-world scenarios.  